### ISSUE TITLE
菜单自动载入成功但不在总列表显示

### ISSUE THREAD

**Issue by GangYiTife** [hamo-reid/nonenot_plugin_PicMenu#33]
在菜单载入时报错：
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_osubot 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_boardgame 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_memes 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_autoreply 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_heweather 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_animalVoice 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_capoo 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_picmcstat 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_starrail_calendar 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_steam_game_status 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_maimai 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_userinfo 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_datastore 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_txt2img 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_jrrp2 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_tarot 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_saa 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | echo 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_handle 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_cloudsignx 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_session 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_htmlrender 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_cchess 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_picstatus 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_minesweeper 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_PicMenu 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_wordle 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_simplemusic 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_localstore 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_pjsk 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_cave 菜单数据已加载 (from code)
09-16 14:32:49 [SUCCESS] nonebot_plugin_PicMenu | nonebot_plugin_chess 菜单数据已加载 (from code)
09-16 14:32:49 [INFO] nonebot_plugin_gocqhttp | [1158338916] 已连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws
09-16 14:32:49 [ERROR] nonebot | Error when running WebSocketConnection hook. Running cancelled!
Traceback (most recent call last):
  File "D:\nb\GYTBOT\bot.py", line 17, in <module>
    nonebot.run()
  File "D:\nb\GYTBOT\.venv\lib\site-packages\nonebot\__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "D:\nb\GYTBOT\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 199, in run
    uvicorn.run(
  File "D:\nb\GYTBOT\.venv\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "D:\nb\GYTBOT\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "D:\nb\GYTBOT\.venv\lib\site-packages\nonebot\internal\driver\driver.py", line 150, in _run_hook
    await asyncio.gather(*coros)
  File "D:\nb\GYTBOT\.venv\lib\site-packages\nonebot\utils.py", line 186, in run_coro_with_catch
    return await coro
  File "D:\nb\GYTBOT\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\nb\GYTBOT\.venv\lib\site-packages\nonebot_plugin_PicMenu\__init__.py", line 21, in _
    menu_manager.load_plugin_info()
  File "D:\nb\GYTBOT\.venv\lib\site-packages\nonebot_plugin_PicMenu\manager.py", line 170, in load_plugin_info
    self.data_manager.load_plugin_info()
  File "D:\nb\GYTBOT\.venv\lib\site-packages\nonebot_plugin_PicMenu\manager.py", line 86, in load_plugin_info
    self.plugin_menu_data_list.sort(key=lambda x: x.name.encode('gbk'))
  File "D:\nb\GYTBOT\.venv\lib\site-packages\nonebot_plugin_PicMenu\manager.py", line 86, in <lambda>
    self.plugin_menu_data_list.sort(key=lambda x: x.name.encode('gbk'))
UnicodeEncodeError: 'gbk' codec can't encode character '\u2601' in position 0: illegal multibyte sequence

![屏幕截图 2023-09-16 143740](https://github.com/hamo-reid/nonebot_plugin_PicMenu/assets/119110925/3f9ab92e-edb7-4eed-ab18-d0780b4dbf5c)
并且总列表无法使用，单个二级菜单可以使用
求解答，谢谢。

**Comment by ABKQPO** [comment]
使用pillow9.5.0
