### ISSUE TITLE
发送菜单失败

### ISSUE THREAD

**Issue by QSlotus** [hamo-reid/nonenot_plugin_PicMenu#35]
发送菜单失败
报错如下
```
02-18 14:16:58 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_PicMenu, lineno=24) failed.
Traceback (most recent call last):
  File "/data/nbot/bot.py", line 15, in <module>
    nonebot.run()
  File "/data/nbot/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "/data/nbot/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 185, in run
    uvicorn.run(
  File "/data/nbot/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/data/nbot/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/data/nbot/.venv/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/data/nbot/.venv/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/data/nbot/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/data/nbot/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 817, in simple_run
    await handler(
  File "/data/nbot/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/data/nbot/.venv/lib/python3.10/site-packages/nonebot_plugin_PicMenu/__init__.py", line 75, in _
    img = menu_manager.generate_main_menu_image()
  File "/data/nbot/.venv/lib/python3.10/site-packages/nonebot_plugin_PicMenu/manager.py", line 189, in generate_main_menu_image
    return template().generate_main_menu(data)
  File "/data/nbot/.venv/lib/python3.10/site-packages/nonebot_plugin_PicMenu/template.py", line 83, in generate_main_menu
    row_size_list = [tuple(
  File "/data/nbot/.venv/lib/python3.10/site-packages/nonebot_plugin_PicMenu/template.py", line 84, in <lambda>
    map(lambda _x: calculate_text_size(_x, self.basic_font_size, self.using_font),
  File "/data/nbot/.venv/lib/python3.10/site-packages/nonebot_plugin_PicMenu/img_tool.py", line 417, in calculate_text_size
    return using_font.getsize(text)
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
```
已配置config.json
```
{"default": "/data/nbot/menu_config/fonts/simhei.ttf"}
```

**Comment by QSlotus** [comment]
已按照[#28]解决
