### ISSUE TITLE
【报错】字体错误

### ISSUE THREAD

**Issue by Agnes4m** [hamo-reid/nonenot_plugin_PicMenu#5]
python3.9.12，nonebot2.0.0b4，gocq=1.0.0-rc3
已修改menu_config/config.json为支持的字体（肯定安装了这个字体）

`{"wqy-zenhei.ttc": "font_path"}`
价值插件正常，使用“菜单帮助”指令出下列错误
```
07-15 11:1707 [IiFO][rnonebot | Matcher clatcher from nonebot_plugin PiClleru, type=rEessoge, priority=l, temp=False runing caplete07-15 11:17:07 [ERROR] monebot l Running matcher clatcher from nonebot_plugin_ PiCclenu, type=Eessage, priority=l, temp=Falseo failed.Traceback (most recent call last):
File "<string>",line 1,in <module>
File " /usr/lib/python3.9/multiprocessing/spawn.py", line 116，in spawn_mainexitcode = _main(fd, parent_sentinel)
File "/usr/lib/python3.9/multiprocessing/spawn.py"，line 129，in _mainreturn self._bootstrap(parent_sentinel)
File "/usr/lib/python3.9/multiprocessing/process.py"，line 315， in _bootstrapself.run(
File " /usr/lib/python3.9/multiprocessing/process.py"，line 108，in runself._target(self._args,**self._kwargs)
File "/usr/iocal/lib/python3.9/dist-packages/uvicorn/subprocess.py"，line 76，in subprocess_startedtarget(sockets=sockets)
File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py"，line 60，in runreturn asyncio.run(self.serve(sockets=sockets))
File "/usr/iib/python3.9/asyncio/runners.py", line 44，in runreturn loop.run_until_complete(main)
File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py"，line 146, in _check_matcherawait _run_matcher(Matcher, bot，event, state， stack,dependency_cache)
>File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py" "， line 196，in _run_matcherawait matcher.run(bot，event,state,stack,，dependency_cache)
File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py",line 668，in runawait self.simple_run(bot,event,state,stack，dependency_cache)
File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py" ,line 635，in simple_runawait handler(.
File "/usr/locai/lib/python3.9/dist-packages/nonebot/dependencies/ ..init..py",line 92,in ..call_.return await self.call(**values)
File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_PicMenu/.init ..py"，line 81，in _img = menu_manager.generate_main_menu_image(
File " /usr/local/itib/python3.9/dist-packages /nonebot_plugin_PicMenu/menus.py"，line 678，in generate_main_meru_imageimg = template().generate_main_menu(data)
File"/usr /local/tib/python3.9/dist-packages/nonebot_plugin_PiaMenu/menus.py"，line 96，in ..init.-self.load_resource(
File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_PicMenu/menus.py"，line 1:8，in load_resourceself.using_font = config[ 'defaulti
KeyError: 'default'

```

我是否应该把字体复制一份到menu_config/fonts/下面？

**Comment by hamo-reid** [comment]
将font_path修改为你字体的路径不是将default修改

**Comment by Agnes4m** [comment]
谢谢，可以 了
